name: Download OpenHarmony SDK
description: Download OpenHarmony SDK for CI/CD workflows
author: Naily Zero
branding:
  icon: arrow-down
  color: blue
inputs:
  version:
    description: SDK version to download, default is `API18`
    required: true
    default: API18
  arch:
    description: SDK architecture, default is `X86`
    required: false
    default: X86
  os:
    description: SDK operating system, default is `Linux`
    required: false
    default: Linux
  cache_dir:
    description: Cache directory for downloaded files, default is `.cache/sdk`
    required: false
    default: .cache/sdk
  target_dir:
    description: Target directory to extract SDK, default is `sdk`
    required: false
    default: sdk
  clean:
    description: Whether to clean cache after download, default is `true`
    required: false
    default: 'true'
  log_type:
    description: 'Log type, (default: explicit), can be explicit, full, or silent'
    required: false
    default: explicit
  log_timeout:
    description: 'Timeout for log output in milliseconds, default is 5000ms'
    required: false
    default: '5000'
  cache:
    description: Whether to cache the downloaded SDK, default is `true`
    required: false
    default: 'true'
outputs:
  sdkPath:
    description: Path to the extracted SDK
runs:
  using: node20
  main: dist/github-action.js
