name: Test SDK Downloader Action

on:
  workflow_dispatch:  # 手动触发
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-action:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Test with explicit logging
      id: test-explicit
      uses: ./
      with:
        version: '4.0.0'
        arch: 'X86'
        os: 'Linux'
        log-type: 'explicit'
        log-timeout: '3000'
        
    - name: Test with silent logging
      id: test-silent
      uses: ./
      with:
        version: '4.0.0'
        arch: 'X86'
        os: 'Linux'
        log-type: 'silent'
        
    - name: Show results
      run: 'echo "Explicit test SDK path: ${{ steps.test-explicit.outputs.sdk-path }}'
