name: Test SDK Downloader Action

on:
  workflow_dispatch:  # 手动触发
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-action:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Testing
      uses: ./
      id: testing
      with:
        version: API18
        arch: X86
        os: Linux
        
    - name: Show results
      run: 'echo "Explicit test SDK path: ${{ steps.testing.outputs.sdk-path }}'
